arrayOfQuotations = [
    "I am not bothered by the fact that I am not understood. I am bothered when I do not know others.  - Confucius",
    "Reviewing what you have learned and learning anew, you are fit to be a teacher.  - Confucius",
    "The Superior Man is all-embracing and not partial. The inferior man is partial and not all-embracing.  - Confucius",
    "To study and not think is a waste. To think and not study is dangerous.  - Confucius",
    "Listen widely to remove your doubts and be careful when speaking about the rest and your mistakes will be few.  - Confucius",
    "When we see men of worth, we should think of equaling them; when we see men of a contrary character, we should turn inwards and examine ourselves.",
    "The cautious seldom err.  - Confucius",
    "The superior man is modest in his speech, but exceeds in his actions.  - Confucius",
    "The Superior Man is aware of Righteousness, the inferior man is aware of advantage.  - Confucius",
    "They who know the truth are not equal to those who love it, and they who love it are not equal to those who delight in it.  - Confucius",
    "To give one's self earnestly to the duties due to men, and, while respecting spiritual beings, to keep aloof from them, may be called wisdom.  - Confucius",
    "The man of virtue makes the difficulty to be overcome his first business, and success only a subsequent consideration: this may be called perfect virtue.  - Confucius",
    "I do not open up the truth to one who is not eager to get knowledge, nor help out any one who is not anxious to explain himself.  - Confucius",
    "When I walk along with two others, they may serve me as my teachers. I will select their good qualities and follow them, their bad qualities and avoid them.  - Confucius",
    "When a country is well governed, poverty and a mean condition are things to be ashamed of. When a country is ill governed, riches and honor are things to be ashamed of  - Confucius.",
    "He who exercises government by means of his virtue may be compared to the north polar star, which keeps its place when all the stars are rotating about it  - Confucius.",
    "The virtuous is frank and open; the non-virtuous is secretive and worrying.  - Confucius",
    "The superior man, when resting in safety, does not forget that danger may come. When in a state of security he does not forget the possibility of ruin.  - Confucius",
    "What you do not want done to yourself, do not do to others.  - Confucius",
    "Only after Winter comes do we know that the pine and the cypress are the last to fade.  - Confucius",
    "Let the states of equilibrium and harmony exist in perfection, and a happy order will prevail throughout heaven and earth, and all things will be nourished and flourish.  - Confucius",
    "When the archer misses the center of the target, he turns round and seeks for the cause of his failure in himself.  - Confucius",
    "In all things success depends on previous preparation, and without such previous preparation there is sure to be failure.  - Confucius",
    "Sincerity is the end and beginning of things; without sincerity there would be nothing.  - Confucius",
    "What the great learning teaches, is to illustrate illustrious virtue; to renovate the people; and to rest in the highest excellence.  - Confucius",
    "To know that we know what we know, and that we do not know what we do not know, that is true knowledge.  - Confucius",
    "The more man meditates upon good thoughts, the better will be his world and the world at large.  - Confucius",
    "It is not truth that makes man great, but man that makes truth great.  - Confucius",
    "Men do not stumble over mountains, but over molehills.  - Confucius",


]