arrayOfQuotations = [
    "A cheerful wife is the spice of life.  - European Proverb",
    "A good mind possesses a kingdom.  - European Proverb",
    "A good name is the best of all treasures.  - European Proverb",
    "The apple never falls far from the tree.  - Proverb",
    "Advice most needed is least heeded.  - American Proverb",
    "Advisers run no risks.  - European Proverb",
    "All are not thieves that the dogs bark at.  - European Proverb",
    "All's fair in love and war.  - American Proverb",
    "All are not friends that speak us fair.  - European Proverb",
    "All roads lead to Rome.  - Proverb",
    "All things come to those who wait.  - Proverb",
    "All work and no play makes Jack a dull boy.  - American Proverb",
    "An army marches on its stomach.  - Proverb",
    "March winds and April showers bring forth May flowers.  - Proverb",
    "As you make your bed, so you must lie on it.  - English Proverb",
    "A hedge between keeps friends green.  - European Proverb",
    "A verbal contract isn't worth the paper it's written on.  - American Proverb",
    "Absence makes the heart grow fonder.  - Thomas Haynes Bayly",
    "Actions speak louder than words.  - American Idiom",
    "A friend in need is a friend indeed.  - John Heywood",
    "All cats love fish but hate to get their paws wet.  - Elizabeth Martyn",
    "All for one and one for all.  - Motto of Switzerland",
    "All good things must come to an end.  - English Proverb",
    "All's well that ends well.  - William Shakespeare",
    "All that glisters is not gold.  - William Shakespeare",
    "A staff is quickly found to beat a dog.  - European Proverb",
    "An apple a day keeps the doctor away.  - Marketing Slogan",
    "As the old cock crows, so crows the young.  - European Proverb",
    "Ask me no questions, I'll tell you no lies.  - Oliver Goldsmith",
    "Bad news travels fast.  - Proverb",
    "A bad penny always turns up.  - Proverb",
    "A bad settlement is better than a good lawsuit.  - M.R. Filipp",
    "Be careful what you wish for, you just might get it.  - A. Potter",
    "Well begun is half done.  - American Proverb",
    "A bellyful is one of meat, drink, or sorrow.  - English Proverb",
    "Bend the willow while it is young.  - Proverb",
    "The best things come in small packages.  - Proverb",
    "The best things in life are free.  - Proverb",
    "Better an egg today than a hen tomorrow.  - European Proverb",
    "Better is the enemy of good.  - American Proverb",
    "Better late than never.  - American Proverb",
    "Better safe than sorry.  - Proverb",
    "Beware of false prophets, who come to you in sheep's clothing, but inwardly they are ravening wolves.  - Jesus",
    "Birds of a feather flock together.  - Proverb",
    "Bitter pills may have blessed effects.  - American Proverb",
    "Blood is thicker than water.  - Proverb",
    "Beauty is in the eyes of the beholder.  - Proverb",
    "A bad workman blames his tools.  - George Herbert",
    "Barking dogs seldom bite.  - English Proverb",
    "Before criticizing a man, walk a mile in his shoes.  - R. Preston Preston",
    "Beggars can't be choosers.  - Kirk Hiner",
    "The belly has no ears.  - Proverb",
    "Better to be alone than in bad company.  - European Proverb",
    "Better the devil you know (than the devil you don't).  - English Proverb & Proverb",
    "Better to remain silent and be thought a fool, than to open your mouth and remove all doubt.  - Abraham Lincoln",
    "Beware of Greeks bearing gifts.  - Virgil",
    "A bird in the hand is worth two in the bush.  - John Bunyan",
    "A blow with a word strikes deeper than a blow with a sword.  - John Burton",
    "Bloom where you are planted.  - Martha Szerlip",
    "Boys will be boys.  - Myriam Miedzian",
    "A broken watch is right two times a day.  - Eve Light Honthaner",
    "A burnt child dreads the fire.  - Nathan Bailer",
    "By hook or by crook.  - John Heywood",
    "The calm comes before the storm.  - American Proverb",
    "Clothes make the man.  - European Proverb",
    "The customer is always right.  - English Proverb",
    "A candle loses nothing by lighting another candle.  - Jan Groft",
    "A chain is only as strong as its weakest link.  - Thomas Reid",
    "The child is father to the man.  - Gerard Manley Hopkins",
    "Common sense is not so comic.  - Voltaire",
    "Courage lost, all lost.  - European Proverb",
    "A coward dies a thousand times before his death. The valiant never taste of death but once.  - Shakespeare"
]