    // Quotation Database Array
    // These are "Category", Difficulty from 1 (easiest) to 5 (hardest), "Quotation")

var quotationBase = [
    ["English Proverb", 2, "A cheerful wife is the spice of life.  - European Proverb"],
    ["English Proverb", 2, "A good mind possesses a kingdom.  - European Proverb"],
    ["English Proverb", 2, "A good name is the best of all treasures.  - European Proverb"],
    ["English Proverb", 2, "The apple never falls far from the tree.  - Proverb"],
    ["English Proverb", 2, "Advice most needed is least heeded.  - American Proverb"],
    ["English Proverb", 2, "Advisers run no risks.  - European Proverb"],
    ["English Proverb", 2, "All are not thieves that the dogs bark at.  - European Proverb"],
    ["English Proverb", 2, "All's fair in love and war.  - American Proverb"],
    ["English Proverb", 2, "All are not friends that speak us fair.  - European Proverb"],
    ["English Proverb", 2, "All roads lead to Rome.  - Proverb"],
    ["English Proverb", 2, "All things come to those who wait.  - Proverb"],
    ["English Proverb", 2, "All work and no play makes Jack a dull boy.  - American Proverb"],
    ["English Proverb", 2, "An army marches on its stomach.  - Proverb"],
    ["English Proverb", 2, "March winds and April showers bring forth May flowers.  - Proverb"],
    ["English Proverb", 2, "As you make your bed, so you must lie on it.  - English Proverb"],
    ["English Proverb", 2, "A hedge between keeps friends green.  - European Proverb"],
    ["English Proverb", 2, "A verbal contract isn't worth the paper it's written on.  - American Proverb"],
    ["English Proverb", 2, "Absence makes the heart grow fonder.  - Thomas Haynes Bayly"],
    ["English Proverb", 2, "Actions speak louder than words.  - American Idiom"],
    ["English Proverb", 2, "A friend in need is a friend indeed.  - John Heywood"],
    ["English Proverb", 2, "All cats love fish but hate to get their paws wet.  - Elizabeth Martyn"],
    ["English Proverb", 2, "All for one and one for all.  - Motto of Switzerland"],
    ["English Proverb", 2, "All good things must come to an end.  - English Proverb"],
    ["English Proverb", 2, "All's well that ends well.  - William Shakespeare"],
    ["English Proverb", 2, "All that glisters is not gold.  - William Shakespeare"],
    ["English Proverb", 2, "A staff is quickly found to beat a dog.  - European Proverb"],
    ["English Proverb", 2, "An apple a day keeps the doctor away.  - Marketing Slogan"],
    ["English Proverb", 2, "As the old cock crows, so crows the young.  - European Proverb"],
    ["English Proverb", 2, "Ask me no questions, I'll tell you no lies.  - Oliver Goldsmith"],
    ["English Proverb", 2, "Bad news travels fast.  - Proverb"],
    ["English Proverb", 2, "A bad penny always turns up.  - Proverb"],
    ["English Proverb", 2, "A bad settlement is better than a good lawsuit.  - M.R. Filipp"],
    ["English Proverb", 2, "Be careful what you wish for, you just might get it.  - A. Potter"],
    ["English Proverb", 2, "Well begun is half done.  - American Proverb"],
    ["English Proverb", 2, "A bellyful is one of meat, drink, or sorrow.  - English Proverb"],
    ["English Proverb", 2, "Bend the willow while it is young.  - Proverb"],
    ["English Proverb", 2, "The best things come in small packages.  - Proverb"],
    ["English Proverb", 2, "The best things in life are free.  - Proverb"],
    ["English Proverb", 2, "Better an egg today than a hen tomorrow.  - European Proverb"],
    ["English Proverb", 2, "Better is the enemy of good.  - American Proverb"],
    ["English Proverb", 2, "Better late than never.  - American Proverb"],
    ["English Proverb", 2, "Better safe than sorry.  - Proverb"],
    ["English Proverb", 2, "Beware of false prophets, who come to you in sheep's clothing, but inwardly they are ravening wolves.  - Jesus"],
    ["English Proverb", 2, "Birds of a feather flock together.  - Proverb"],
    ["English Proverb", 2, "Bitter pills may have blessed effects.  - American Proverb"],
    ["English Proverb", 2, "Blood is thicker than water.  - Proverb"],
    ["English Proverb", 2, "Beauty is in the eyes of the beholder.  - Proverb"],
    ["English Proverb", 2, "A bad workman blames his tools.  - George Herbert"],
    ["English Proverb", 2, "Barking dogs seldom bite.  - English Proverb"],
    ["English Proverb", 2, "Before criticizing a man, walk a mile in his shoes.  - R. Preston Preston"],
    ["English Proverb", 2, "Beggars can't be choosers.  - Kirk Hiner"],
    ["English Proverb", 2, "The belly has no ears.  - Proverb"],
    ["English Proverb", 2, "Better to be alone than in bad company.  - European Proverb"],
    ["English Proverb", 2, "Better the devil you know (than the devil you don't).  - English Proverb & Proverb"],
    ["English Proverb", 2, "Better to remain silent and be thought a fool, than to open your mouth and remove all doubt.  - Abraham Lincoln"],
    ["English Proverb", 2, "Beware of Greeks bearing gifts.  - Virgil"],
    ["English Proverb", 2, "A bird in the hand is worth two in the bush.  - John Bunyan"],
    ["English Proverb", 2, "A blow with a word strikes deeper than a blow with a sword.  - John Burton"],
    ["English Proverb", 2, "Bloom where you are planted.  - Martha Szerlip"],
    ["English Proverb", 2, "Boys will be boys.  - Myriam Miedzian"],
    ["English Proverb", 2, "A broken watch is right two times a day.  - Eve Light Honthaner"],
    ["English Proverb", 2, "A burnt child dreads the fire.  - Nathan Bailer"],
    ["English Proverb", 2, "By hook or by crook.  - John Heywood"],
    ["English Proverb", 2, "The calm comes before the storm.  - American Proverb"],
    ["English Proverb", 2, "Clothes make the man.  - European Proverb"],
    ["English Proverb", 2, "The customer is always right.  - English Proverb"],
    ["English Proverb", 2, "A candle loses nothing by lighting another candle.  - Jan Groft"],
    ["English Proverb", 2, "A chain is only as strong as its weakest link.  - Thomas Reid"],
    ["English Proverb", 2, "The child is father to the man.  - Gerard Manley Hopkins"],
    ["English Proverb", 2, "Common sense is not so comic.  - Voltaire"],
    ["English Proverb", 2, "Courage lost, all lost.  - European Proverb"],
    ["English Proverb", 2, "A coward dies a thousand times before his death. The valiant never taste of death but once.  - Shakespeare"],
    ["Confucius", 4, "I am not bothered by the fact that I am not understood. I am bothered when I do not know others.  - Confucius"],
    ["Confucius", 4, "Reviewing what you have learned and learning anew, you are fit to be a teacher.  - Confucius"],
    ["Confucius", 4, "The Superior Man is all-embracing and not partial. The inferior man is partial and not all-embracing.  - Confucius"],
    ["Confucius", 4, "To study and not think is a waste. To think and not study is dangerous.  - Confucius"],
    ["Confucius", 4, "Listen widely to remove your doubts and be careful when speaking about the rest and your mistakes will be few.  - Confucius"],
    ["Confucius", 4, "When we see men of worth, we should think of equaling them; when we see men of a contrary character, we should turn inwards and examine ourselves.  - Confucius"],
    ["Confucius", 4, "The cautious seldom err.  - Confucius"],
    ["Confucius", 4, "The superior man is modest in his speech, but exceeds in his actions.  - Confucius"],
    ["Confucius", 4, "The Superior Man is aware of Righteousness, the inferior man is aware of advantage.  - Confucius"],
    ["Confucius", 4, "They who know the truth are not equal to those who love it, and they who love it are not equal to those who delight in it.  - Confucius"],
    ["Confucius", 4, "To give one's self earnestly to the duties due to men, and, while respecting spiritual beings, to keep aloof from them, may be called wisdom.  - Confucius"],
    ["Confucius", 4, "The man of virtue makes the difficulty to be overcome his first business, and success only a subsequent consideration: this may be called perfect virtue.  - Confucius"],
    ["Confucius", 4, "I do not open up the truth to one who is not eager to get knowledge, nor help out any one who is not anxious to explain himself.  - Confucius"],
    ["Confucius", 4, "When I walk along with two others, they may serve me as my teachers. I will select their good qualities and follow them, their bad qualities and avoid them.  - Confucius"],
    ["Confucius", 4, "When a country is well governed, poverty and a mean condition are things to be ashamed of. When a country is ill governed, riches and honor are things to be ashamed of  - Confucius."],
    ["Confucius", 4, "He who exercises government by means of his virtue may be compared to the north polar star, which keeps its place when all the stars are rotating about it  - Confucius."],
    ["Confucius", 4, "The virtuous is frank and open; the non-virtuous is secretive and worrying.  - Confucius"],
    ["Confucius", 4, "The superior man, when resting in safety, does not forget that danger may come. When in a state of security he does not forget the possibility of ruin.  - Confucius"],
    ["Confucius", 4, "What you do not want done to yourself, do not do to others.  - Confucius"],
    ["Confucius", 4, "Only after Winter comes do we know that the pine and the cypress are the last to fade.  - Confucius"],
    ["Confucius", 4, "Let the states of equilibrium and harmony exist in perfection, and a happy order will prevail throughout heaven and earth, and all things will be nourished and flourish.  - Confucius"],
    ["Confucius", 4, "When the archer misses the center of the target, he turns round and seeks for the cause of his failure in himself.  - Confucius"],
    ["Confucius", 4, "In all things success depends on previous preparation, and without such previous preparation there is sure to be failure.  - Confucius"],
    ["Confucius", 4, "Sincerity is the end and beginning of things; without sincerity there would be nothing.  - Confucius"],
    ["Confucius", 4, "What the great learning teaches, is to illustrate illustrious virtue; to renovate the people; and to rest in the highest excellence.  - Confucius"],
    ["Confucius", 4, "To know that we know what we know, and that we do not know what we do not know, that is true knowledge.  - Confucius"],
    ["Confucius", 4, "The more man meditates upon good thoughts, the better will be his world and the world at large.  - Confucius"],
    ["Confucius", 4, "It is not truth that makes man great, but man that makes truth great.  - Confucius"],
    ["Confucius", 4, "Men do not stumble over mountains, but over molehills.  - Confucius"],

]