    // Quotation Database Array
    // These are "Category", Difficulty from 1 (easiest) to 5 (hardest), "Quotation")

var quotationBase = [
    ["English Proverb", 2, "A cheerful wife is the spice of life.  - European Proverb"],
    ["English Proverb", 2, "A good mind possesses a kingdom.  - European Proverb"],
    ["English Proverb", 2, "A good name is the best of all treasures.  - European Proverb"],
    ["English Proverb", 2, "The apple never falls far from the tree.  - Proverb"],
    ["English Proverb", 2, "Advice most needed is least heeded.  - American Proverb"],
    ["English Proverb", 2, "Advisers run no risks.  - European Proverb"],
    ["English Proverb", 2, "All are not thieves that the dogs bark at.  - European Proverb"],
    ["English Proverb", 2, "All's fair in love and war.  - American Proverb"],
    ["English Proverb", 2, "All are not friends that speak us fair.  - European Proverb"],
    ["English Proverb", 2, "All roads lead to Rome.  - Proverb"],
    ["English Proverb", 2, "All things come to those who wait.  - Proverb"],
    ["English Proverb", 2, "All work and no play makes Jack a dull boy.  - American Proverb"],
    ["English Proverb", 2, "An army marches on its stomach.  - Proverb"],
    ["English Proverb", 2, "March winds and April showers bring forth May flowers.  - Proverb"],
    ["English Proverb", 2, "As you make your bed, so you must lie on it.  - English Proverb"],
    ["English Proverb", 2, "A hedge between keeps friends green.  - European Proverb"],
    ["English Proverb", 2, "A verbal contract isn't worth the paper it's written on.  - American Proverb"],
    ["English Proverb", 2, "Absence makes the heart grow fonder.  - Thomas Haynes Bayly"],
    ["English Proverb", 2, "Actions speak louder than words.  - American Idiom"],
    ["English Proverb", 2, "A friend in need is a friend indeed.  - John Heywood"],
    ["English Proverb", 2, "All cats love fish but hate to get their paws wet.  - Elizabeth Martyn"],
    ["English Proverb", 2, "All for one and one for all.  - Motto of Switzerland"],
    ["English Proverb", 2, "All good things must come to an end.  - English Proverb"],
    ["English Proverb", 2, "All's well that ends well.  - William Shakespeare"],
    ["English Proverb", 2, "All that glisters is not gold.  - William Shakespeare"],
    ["English Proverb", 2, "A staff is quickly found to beat a dog.  - European Proverb"],
    ["English Proverb", 2, "An apple a day keeps the doctor away.  - Marketing Slogan"],
    ["English Proverb", 2, "As the old cock crows, so crows the young.  - European Proverb"],
    ["English Proverb", 2, "Ask me no questions, I'll tell you no lies.  - Oliver Goldsmith"],
    ["English Proverb", 2, "Bad news travels fast.  - Proverb"],
    ["English Proverb", 2, "A bad penny always turns up.  - Proverb"],
    ["English Proverb", 2, "A bad settlement is better than a good lawsuit.  - M.R. Filipp"],
    ["English Proverb", 2, "Be careful what you wish for, you just might get it.  - A. Potter"],
    ["English Proverb", 2, "Well begun is half done.  - American Proverb"],
    ["English Proverb", 2, "A bellyful is one of meat, drink, or sorrow.  - English Proverb"],
    ["English Proverb", 2, "Bend the willow while it is young.  - Proverb"],
    ["English Proverb", 2, "The best things come in small packages.  - Proverb"],
    ["English Proverb", 2, "The best things in life are free.  - Proverb"],
    ["English Proverb", 2, "Better an egg today than a hen tomorrow.  - European Proverb"],
    ["English Proverb", 2, "Better is the enemy of good.  - American Proverb"],
    ["English Proverb", 2, "Better late than never.  - American Proverb"],
    ["English Proverb", 2, "Better safe than sorry.  - Proverb"],
    ["English Proverb", 2, "Beware of false prophets, who come to you in sheep's clothing, but inwardly they are ravening wolves.  - Jesus"],
    ["English Proverb", 2, "Birds of a feather flock together.  - Proverb"],
    ["English Proverb", 2, "Bitter pills may have blessed effects.  - American Proverb"],
    ["English Proverb", 2, "Blood is thicker than water.  - Proverb"],
    ["English Proverb", 2, "Beauty is in the eyes of the beholder.  - Proverb"],
    ["English Proverb", 2, "A bad workman blames his tools.  - George Herbert"],
    ["English Proverb", 2, "Barking dogs seldom bite.  - English Proverb"],
    ["English Proverb", 2, "Before criticizing a man, walk a mile in his shoes.  - R. Preston Preston"],
    ["English Proverb", 2, "Beggars can't be choosers.  - Kirk Hiner"],
    ["English Proverb", 2, "The belly has no ears.  - Proverb"],
    ["English Proverb", 2, "Better to be alone than in bad company.  - European Proverb"],
    ["English Proverb", 2, "Better the devil you know (than the devil you don't).  - English Proverb & Proverb"],
    ["English Proverb", 2, "Better to remain silent and be thought a fool, than to open your mouth and remove all doubt.  - Abraham Lincoln"],
    ["English Proverb", 2, "Beware of Greeks bearing gifts.  - Virgil"],
    ["English Proverb", 2, "A bird in the hand is worth two in the bush.  - John Bunyan"],
    ["English Proverb", 2, "A blow with a word strikes deeper than a blow with a sword.  - John Burton"],
    ["English Proverb", 2, "Bloom where you are planted.  - Martha Szerlip"],
    ["English Proverb", 2, "Boys will be boys.  - Myriam Miedzian"],
    ["English Proverb", 2, "A broken watch is right two times a day.  - Eve Light Honthaner"],
    ["English Proverb", 2, "A burnt child dreads the fire.  - Nathan Bailer"],
    ["English Proverb", 2, "By hook or by crook.  - John Heywood"],
    ["English Proverb", 2, "The calm comes before the storm.  - American Proverb"],
    ["English Proverb", 2, "Clothes make the man.  - European Proverb"],
    ["English Proverb", 2, "The customer is always right.  - English Proverb"],
    ["English Proverb", 2, "A candle loses nothing by lighting another candle.  - Jan Groft"],
    ["English Proverb", 2, "A chain is only as strong as its weakest link.  - Thomas Reid"],
    ["English Proverb", 2, "The child is father to the man.  - Gerard Manley Hopkins"],
    ["English Proverb", 2, "Common sense is not so comic.  - Voltaire"],
    ["English Proverb", 2, "Courage lost, all lost.  - European Proverb"],
    ["English Proverb", 2, "A coward dies a thousand times before his death. The valiant never taste of death but once.  - Shakespeare"],
    ["Confucius", 4, "I am not bothered by the fact that I am not understood. I am bothered when I do not know others.  - Confucius"],
    ["Confucius", 4, "Reviewing what you have learned and learning anew, you are fit to be a teacher.  - Confucius"],
    ["Confucius", 4, "The Superior Man is all-embracing and not partial. The inferior man is partial and not all-embracing.  - Confucius"],
    ["Confucius", 4, "To study and not think is a waste. To think and not study is dangerous.  - Confucius"],
    ["Confucius", 4, "Listen widely to remove your doubts and be careful when speaking about the rest and your mistakes will be few.  - Confucius"],
    ["Confucius", 4, "When we see men of worth, we should think of equaling them; when we see men of a contrary character, we should turn inwards and examine ourselves.  - Confucius"],
    ["Confucius", 4, "The cautious seldom err.  - Confucius"],
    ["Confucius", 4, "The superior man is modest in his speech, but exceeds in his actions.  - Confucius"],
    ["Confucius", 4, "The Superior Man is aware of Righteousness, the inferior man is aware of advantage.  - Confucius"],
    ["Confucius", 4, "They who know the truth are not equal to those who love it, and they who love it are not equal to those who delight in it.  - Confucius"],
    ["Confucius", 4, "To give one's self earnestly to the duties due to men, and, while respecting spiritual beings, to keep aloof from them, may be called wisdom.  - Confucius"],
    ["Confucius", 4, "The man of virtue makes the difficulty to be overcome his first business, and success only a subsequent consideration: this may be called perfect virtue.  - Confucius"],
    ["Confucius", 4, "I do not open up the truth to one who is not eager to get knowledge, nor help out any one who is not anxious to explain himself.  - Confucius"],
    ["Confucius", 4, "When I walk along with two others, they may serve me as my teachers. I will select their good qualities and follow them, their bad qualities and avoid them.  - Confucius"],
    ["Confucius", 4, "When a country is well governed, poverty and a mean condition are things to be ashamed of. When a country is ill governed, riches and honor are things to be ashamed of  - Confucius."],
    ["Confucius", 4, "He who exercises government by means of his virtue may be compared to the north polar star, which keeps its place when all the stars are rotating about it  - Confucius."],
    ["Confucius", 4, "The virtuous is frank and open; the non-virtuous is secretive and worrying.  - Confucius"],
    ["Confucius", 4, "The superior man, when resting in safety, does not forget that danger may come. When in a state of security he does not forget the possibility of ruin.  - Confucius"],
    ["Confucius", 4, "What you do not want done to yourself, do not do to others.  - Confucius"],
    ["Confucius", 4, "Only after Winter comes do we know that the pine and the cypress are the last to fade.  - Confucius"],
    ["Confucius", 4, "Let the states of equilibrium and harmony exist in perfection, and a happy order will prevail throughout heaven and earth, and all things will be nourished and flourish.  - Confucius"],
    ["Confucius", 4, "When the archer misses the center of the target, he turns round and seeks for the cause of his failure in himself.  - Confucius"],
    ["Confucius", 4, "In all things success depends on previous preparation, and without such previous preparation there is sure to be failure.  - Confucius"],
    ["Confucius", 4, "Sincerity is the end and beginning of things; without sincerity there would be nothing.  - Confucius"],
    ["Confucius", 4, "What the great learning teaches, is to illustrate illustrious virtue; to renovate the people; and to rest in the highest excellence.  - Confucius"],
    ["Confucius", 4, "To know that we know what we know, and that we do not know what we do not know, that is true knowledge.  - Confucius"],
    ["Confucius", 4, "The more man meditates upon good thoughts, the better will be his world and the world at large.  - Confucius"],
    ["Confucius", 4, "It is not truth that makes man great, but man that makes truth great.  - Confucius"],
    ["Confucius", 4, "Men do not stumble over mountains, but over molehills.  - Confucius"],

    ["Einstein", 2, "A happy man is too satisfied with the present to dwell too much on the future. - Albert Einstein"],
    ["Einstein", 2, "Unthinking respect for authority is the greatest enemy of truth. - Albert Einstein"],
    ["Einstein", 2, "Nature shows us only the tail of the lion. - Albert Einstein"],
    ["Einstein", 2, "How I wish that somewhere there existed an island for those who are wise and of good will! In such a place even I should be an ardent patriot! - Albert Einstein"],
    ["Einstein", 2, "It's convenient with that fellow Einstein, every year he retracts what he wrote the year before. - Albert Einstein"],
    ["Einstein", 2, "Technological progress is like an axe in the hands of a pathological criminal. - Albert Einstein"],
    ["Einstein", 2, "Make a lot of walks to get healthy and don’t read that much but save yourself some until you’re grown up. - Albert Einstein"],
    ["Einstein", 2, "If my theory of relativity is proven successful, Germany will claim me as a German and France will declare that I am a citizen of the world. Should my theory prove untrue, France will say that I am a German and Germany will declare that I am a Jew. - Albert Einstein"],
    ["Einstein", 2, "In the temple of science are many mansions, and various indeed are they that dwell therein and the motives that have led them thither. - Albert Einstein"],
    ["Einstein", 2, "The state of mind which enables a man to do work of this kind is akin to that of the religious worshiper or the lover - Albert Einstein"],
    ["Einstein", 2, "Man tries to make for himself in the fashion that suits him best a simplified and intelligible picture of the world - Albert Einstein"],
    ["Einstein", 2, "The supreme task of the physicist is to arrive at those universal elementary laws from which the cosmos can be built up by pure deduction. - Albert Einstein"],
    ["Einstein", 2, "Subtle is the Lord, but malicious He is not. - Albert Einstein"],
    ["Einstein", 2, "I do not carry such information in my mind since it is readily available in books. - Albert Einstein"],
    ["Einstein", 2, "The value of a college education is not the learning of many facts but the training of the mind to think. - Albert Einstein"],
    ["Einstein", 2, "In so far as theories of mathematics speak about reality, they are not certain, and in so far as they are certain, they do not speak about reality. - Albert Einstein"],
    ["Einstein", 2, "As I have said so many times, God doesn't play dice with the world. - Albert Einstein"],
    ["Einstein", 2, "Whether you can observe a thing or not depends on the theory which you use. It is the theory which decides what can be observed. - Albert Einstein"],
    ["Einstein", 2, "I believe in Spinoza's God, Who reveals Himself in the lawful harmony of the world, not in a God Who concerns Himself with the fate and the doings of mankind. - Albert Einstein"],
    ["Einstein", 2, "If A is success in life, then A = x + y + z. Work is x, play is y and z is keeping your mouth shut. - Albert Einstein"],
    ["Einstein", 2, "I refuse to make money out of my science. My laurel is not for sale like so many bales of cotton. - Albert Einstein"],
    ["Einstein", 2, "No man can visualize four dimensions, except mathematically … I think in four dimensions, but only abstractly. - Albert Einstein"],
    ["Einstein", 2, "Sometimes one pays most for the things one gets for nothing. - Albert Einstein"],
    ["Einstein", 2, "If I were not a physicist, I would probably be a musician. - Albert Einstein"],
    ["Einstein", 2, "Reading after a certain age diverts the mind too much from its creative pursuits. - Albert Einstein"],
    ["Einstein", 2, "Any man who reads too much and uses his own brain too little falls into lazy habits of thinking - Albert Einstein"],
    ["Einstein", 2, "In America, more than anywhere else, the individual is lost in the achievements of the many. - Albert Einstein"],
    ["Einstein", 2, "Too many of us look upon Americans as dollar chasers. This is a cruel libel, even if it is reiterated thoughtlessly by the Americans themselves. - Albert Einstein"],
    ["Einstein", 2, "We are inclined to overemphasize the material influences in history. - Albert Einstein"],
    ["Einstein", 2, "I am a determinist. As such, I do not believe in free will. - Albert Einstein"],
    ["Einstein", 2, "The only progress I can see is progress in organization. - Albert Einstein"],
    ["Einstein", 2, "Being both a father and teacher, I know we can teach our children nothing. We can transmit to them neither our knowledge of life nor of mathematics. Each must learn its lesson anew. - Albert Einstein"],
    ["Einstein", 2, "I believe in intuitions and inspirations. I sometimes feel that I am right. I do not know that I am. - Albert Einstein"],
    ["Einstein", 2, "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world. - Albert Einstein"],
    ["Einstein", 2, "Nationalism is an infantile disease. It is the measles of mankind. - Albert Einstein"],
    ["Einstein", 2, "Standardization robs life of its spice. - Albert Einstein"],
    ["Einstein", 2, "I believe in standardizing automobiles. I do not believe in standardizing human beings. - Albert Einstein"],
    ["Einstein", 2, "Life is like riding a bicycle. To keep your balance you must keep moving. - Albert Einstein"],
    ["Einstein", 2, "I believe that whatever we do or live for has its causality; it is good, however, that we cannot see through to it. - Albert Einstein"],
    ["Einstein", 2, "The really good music, whether of the East or of the West, cannot be analyzed. - Albert Einstein"],
    ["Einstein", 2, "I never think of the future. It comes soon enough. - Albert Einstein"],
    ["Einstein", 2, "A dictatorship means muzzles all round and consequently stultification. Science can flourish only in an atmosphere of free speech. - Albert Einstein"],
    ["Einstein", 2, "The belief in an external world independent of the perceiving subject is the basis of all natural science. - Albert Einstein"],
    ["Einstein", 2, "Why does this magnificent applied science which saves work and makes life easier bring us so little happiness? The simple answer runs: Because we have not yet learned to make sensible use of it. - Albert Einstein"],
    ["Einstein", 2, "Everyone sits in the prison of his own ideas; he must burst it open, and that in his youth, and so try to test his ideas on reality. - Albert Einstein"],
    ["Einstein", 2, "I see a clock, but I cannot envision the clockmaker. - Albert Einstein"],
    ["Einstein", 2, "Although I am a typical loner in daily life, my consciousness of belonging to the invisible community of those who strive for truth, beauty, and justice has preserved me from feeling isolated. - Albert Einstein"],
    ["Einstein", 2, "Only a life lived for others is a life worthwhile. - Albert Einstein"],
    ["Einstein", 2, "I take it to be true that pure thought can grasp the real, as the ancients had dreamed. - Albert Einstein"],
    ["Einstein", 2, "Everything should be made as simple as possible, but no simpler. - Albert Einstein"],
    ["Einstein", 2, "Force always attracts men of low morality. - Albert Einstein"],
    ["Einstein", 2, "There is not the slightest indication that [nuclear energy] will ever be obtainable. It would mean that the atom would have to be shattered at will. - Albert Einstein"],
    ["Einstein", 2, "I never failed in mathematics. Before I was fifteen I had mastered differential and integral calculus. - Albert Einstein"],
    ["Einstein", 2, "All of science is nothing more than the refinement of everyday thinking. - Albert Einstein"],
    ["Einstein", 2, "One may say the eternal mystery of the world is its comprehensibility. - Albert Einstein"],
    ["Einstein", 2, "Everyone who is seriously involved in the pursuit of science becomes convinced that some spirit is manifest in the laws of the universe, one that is vastly superior to that of man. - Albert Einstein"],
    ["Einstein", 2, "All religions, arts and sciences are branches of the same tree. - Albert Einstein"],
    ["Einstein", 2, "Generations to come, it may well be, will scarce believe that such a man as this one ever in flesh and blood walked upon this Earth. - Albert Einstein"],
    ["Einstein", 2, "I have only two rules which I regard as principles of conduct. The first is: Have no rules. The second is: Be independent of the opinion of others. - Albert Einstein"],
    ["Einstein", 2, "Everything that men do or think concerns the satisfaction of the needs they feel or the escape from pain. - Albert Einstein"],
    ["Einstein", 2, "I assert that the cosmic religious experience is the strongest and noblest driving force behind scientific research. - Albert Einstein"],
    ["Einstein", 2, "A hundred times every day I remind myself that my inner and outer life are based on the labors of other men, living and dead, and that I must exert myself in order to give in the same measure as I have received and am still receiving. - Albert Einstein"],
    ["Einstein", 2, "I regard class differences as contrary to justice and, in the last resort, based on force. I also consider that plain living is good for everybody, physically and mentally. - Albert Einstein"],
    ["Einstein", 2, "In human freedom in the philosophical sense I am definitely a disbeliever. - Albert Einstein"],
    ["Einstein", 2, "Pure mathematics is, in its way, the poetry of logical ideas. - Albert Einstein"]



]